### ISSUE TITLE
Database design technical debt master ticket

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/opal-ideas#21]
Things we need to do: 
- [x] Tagging should have an archived mode (openhealthcare/opal#347)
- [ ] Move core models back to OPAL (openhealthcare/opal#268)
- [ ] Make things that should be FKorFT FKorFT (openhealthcare/elcid#214)
- [ ] Rename MicrobiologyInput & MicrobiologyTest to ClinicalAdvice & Investigation (openhealthcare/elcid#647)
- [ ] Rename all the OPAL core lookuplists to remove the underscores
- [ ] Move OPAT referral information out of elcid.models.Location
- [ ] Refactor Episode start/end/duration fields so that we can order properly

/cc @fredkingham

**Comment by fredkingham** [comment]
Change episodes that we have 1 start date, 1  end date (which can be the same date for single day episodes).

Might also be worth putting in a start time, end time

we'll then order_by("end date", "end time", "created")

then we could have active as a filter between those dates

**Comment by fredkingham** [comment]
take a look at tagging, I think we need archived to be kept in the table as reversion will slow us down cronically I reckon.

I'm tempted to just making tagging a through between Team and Episode and put the "Mine" field on the user profile object. I haven't really thought the last bit through but it sounds good. Thoughts?

**Comment by davidmiller** [comment]
I'm very tempted to make User an optional parameter and not pass it around everywhere given that it's often not required at all!

**Comment by fredkingham** [comment]
sounds good.

Also should we collapse Demographics into Patient
